Integrate mayhem fuzzer
mayhemheroes/wain pull request #1
Opened 2022-04-25 20:01 UTC by harshavamsi

Added dockerfile, github actions, and mayhem files for all the fuzz tests to be integrated with Mayhem.

2022-05-05 06:03 UTC, xansec requested changes

2022-05-05 06:03 UTC, xansec commented on fuzz/Cargo.toml
> -[[bin]]
@harshavamsi , is it possible to run this target without modifications to the `Cargo.toml`? We want to merge into upstream so it's not a good idea to modify these files if we can help it.

2022-05-05 23:15 UTC, harshavamsi commented on fuzz/Cargo.toml
> -[[bin]]
@xansec it turns out they have this additional runner in their cargo file but do not actually have this fuzz test written. Trying to execute the fuzz tests actually fails. The mayhem integration will not pass the fuzz tests.

2022-05-06 01:43 UTC, xansec commented on fuzz/Cargo.toml
> -[[bin]]
It looks like in your `Dockerfile` you run `cargo fuzz build`. You can run `cargo fuzz build <target_name1> <target_name2> ` to only build the targets in question.

2022-05-06 15:51 UTC, harshavamsi commented on fuzz/Cargo.toml
> -[[bin]]
yeah, you're right. I've fixed those changes and now the build passes without editing the Cargo file!

2022-05-06 16:03 UTC, xansec commented on fuzz/Cargo.toml
> -[[bin]]
Awesome! LGTM!

2022-05-06 16:03 UTC, merged